# Generated by Django 4.2.11 on 2024-04-25 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0003_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
