# Generated by Django 4.2.11 on 2024-04-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0004_delete_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('testimonio', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
